apiVersion: v1
kind: ConfigMap
metadata:
  name: valuesource-configmap
data:
  mykey: A1
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-valuefrom-in-param
spec:
  params:
  - name: message
  steps:
  - name: build
    image: mirror.gcr.io/bash
    script: |
      echo "$(params.message)"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-valuefrom-in-param
spec:
  params:
  - name: message
  tasks:
  - name: task1
    params:
      - name: message
        value: $(params.message)
    taskRef:
      name: task-valuefrom-in-param
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelinerun-valuefrom-in-param
spec:
  pipelineRef:
    name: pipeline-valuefrom-in-param
  params:
    - name: message
      valueFrom:
        configMapKeyRef:
          name: valuesource-configmap
          key: mykey
